name: Test

on: [ pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copy repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install pipenv
        run: pipx install pipenv

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pipenv"
      - name: Install dependencies
        run: pipenv install --dev

      - name: Run Test Suite
        run: pipenv run pytest lsn/$(pipenv run python helper/gh_actions.py ${{ github.event.pull_request.title }})*/tests
        env:
          ENVIRONMENT: INTEGRATION
